#Octomap Parameters
octo/tfFrame: /map
octo/robotFrame: /sensor_at_scan
octo/resolution: 0.3
octo/probabilityHit: 0.65
octo/probabilityMiss: 0.4 #加减概率值
octo/thresholdMin: 0.12
octo/thresholdMax: 0.97 #确定上下限
octo/thresholdOccupancy: 0.7
octo/filterSpeckles: true
octo/maxFreeSpace: 0.0
octo/minHeightFreeSpace: 0.0
octo/sensorMaxRange: 5.0
octo/visualizeMinZ: -25.0
octo/visualizeMaxZ: 2.5
octo/mapPublishFrequency: 1.0
octo/treatUnknownAsOccupied: false
octo/changeDetectionEnabled: false
octo/velodyne_cloud_topic: /sensor_scan
